import { authService, projectRepository } from './firebase-repository.js';

  const BACKUP_KEY = 'amano-web-schedule-last-backup';
  const TYPES = {
    internal: { label: '自社作業', className: 'type-internal' },
    client: { label: 'クライアント確認', className: 'type-client' },
    photo: { label: '撮影', className: 'type-photo' },
    milestone: { label: 'マイルストーン', className: 'type-milestone' },
  };

  function uid(prefix) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`; }
  function parseDate(value) { const [y, m, d] = value.split('-').map(Number); return new Date(Date.UTC(y, m - 1, d)); }
  function iso(date) { return date.toISOString().slice(0, 10); }
  function addDays(value, amount) { const d = parseDate(value); d.setUTCDate(d.getUTCDate() + amount); return iso(d); }
  function daysBetween(a, b) { return Math.round((parseDate(b) - parseDate(a)) / 86400000); }
  function formatDate(value, short = false) { if (!value) return '—'; const d = parseDate(value); return new Intl.DateTimeFormat('ja-JP', short ? { month: 'numeric', day: 'numeric' } : { year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); }
  function todayISO() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>'\"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '\"': '&quot;' }[c])); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }

  const state = { projects: [], zoom: 'week', cascade: false, modal: null, user: null, saving: false, error: '' };
  const app = document.getElementById('app');
  async function saveProject(project) {
    state.saving = true;
    try { await projectRepository.saveProject(clone(project)); project.updatedAt = new Date().toISOString(); }
    catch (error) { console.error(error); state.error = '保存できませんでした。通信状態を確認してください。'; }
    finally { state.saving = false; render(); }
  }
  function projectById(id) { return state.projects.find(project => project.id === id); }
  function currentRoute() { const parts = location.hash.replace(/^#\/?/, '').split('/').filter(Boolean); if (parts[0] === 'project' && parts[1]) return { page: 'editor', id: parts[1] }; if (parts[0] === 'preview' && parts[1]) return { page: 'preview', id: parts[1] }; return { page: 'list' }; }
  function navigate(path) { location.hash = path; }
  function render() { const route = currentRoute(); document.body.classList.toggle('preview-mode', route.page === 'preview'); if (route.page === 'editor') renderEditor(route.id); else if (route.page === 'preview') renderPreview(route.id); else renderList(); bindGlobalActions(); }
  function topbar(extra = '') { return `<header class="topbar"><button class="brand brand-button" data-action="home" aria-label="案件一覧へ">制作スケジュール <small>Phase 1.5</small></button><div class="topbar-actions">${state.saving ? '<span class="sync-state">保存中…</span>' : ''}${extra}<button class="btn btn-dark" data-action="data">データ管理</button><button class="btn btn-dark" data-action="logout">ログアウト</button></div></header>${state.error ? `<div class="error-banner">${escapeHtml(state.error)}</div>` : ''}`; }

  function renderList() {
    const rows = state.projects.map(project => `<button class="project-row" type="button" data-action="open-project" data-id="${project.id}"><span><span class="cell-label">案件名</span><span class="project-name">${escapeHtml(project.name)}</span></span><span><span class="cell-label">クライアント名</span>${escapeHtml(project.clientName)}</span><span><span class="cell-label">公開予定日</span>${escapeHtml(project.publishLabel || formatDate(project.publishDate))}</span><span><span class="cell-label">ステータス</span><span class="status">${escapeHtml(project.status)}</span></span><span><span class="cell-label">最終更新日</span>${formatDate(project.updatedAt.slice(0, 10))}</span><span class="arrow">›</span></button>`).join('');
    app.innerHTML = `<div class="app-shell">${topbar()}<main class="page"><div class="page-head"><div><div class="eyebrow">PROJECTS</div><h1>案件一覧</h1><p class="page-sub">制作中の案件と公開予定を確認できます。</p></div><button class="btn btn-primary" data-action="new-project">＋ 新規案件作成</button></div><section class="project-card">${rows || '<div class="empty">案件がありません。</div>'}</section><p class="storage-note">Firebaseへ自動保存され、許可されたスタッフのPC間で共有されます。JSONバックアップも利用できます。</p></main>${modalHtml()}</div>`;
  }

  function renderEditor(id) {
    const project = projectById(id); if (!project) { navigate(''); return; }
    const bounds = timelineBounds(project); const dayWidth = zoomDayWidth(state.zoom, bounds.days); const width = Math.max(1, bounds.days * dayWidth); const gridClass = state.zoom === 'day' ? 'grid-day' : state.zoom === 'week' ? 'grid-week' : 'grid-month';
    app.innerHTML = `<div class="app-shell">${topbar(`<button class="btn btn-dark" data-action="preview" data-id="${project.id}">A4プレビュー</button>`)}<main class="editor-page"><div class="editor-head"><div><button class="back-link" data-action="home">← 案件一覧</button><h1>${escapeHtml(project.name)}</h1><p>${escapeHtml(project.clientName)} <span>・</span> 公開予定 ${escapeHtml(project.publishLabel || formatDate(project.publishDate))}</p></div><button class="btn" data-action="edit-project" data-id="${project.id}">案件情報を編集</button></div><div class="toolbar"><div class="segmented" aria-label="表示単位">${zoomButtons()}</div><label class="cascade"><input type="checkbox" data-action="cascade" ${state.cascade ? 'checked' : ''}><span>後の工程も一緒にずらす</span></label><div class="toolbar-spacer"></div><button class="btn" data-action="preview" data-id="${project.id}">A4プレビュー</button><button class="btn btn-primary" data-action="new-task">＋ 工程追加</button></div><div class="gantt-card"><div class="gantt-label-head">工程 <span>${project.tasks.length}件</span></div><div class="timeline-head-wrap"><div class="timeline-head" style="width:${width}px">${timelineHeader(bounds, dayWidth)}</div></div><div class="gantt-labels">${project.tasks.map((t, i) => taskLabel(t, i, project.tasks.length)).join('')}</div><div class="timeline-scroll" data-day-width="${dayWidth}" data-start="${bounds.start}"><div class="timeline-grid ${gridClass}" style="--day-width:${dayWidth}px;width:${width}px">${project.tasks.map((t, i) => taskRow(t, i, bounds, dayWidth)).join('')}</div></div></div><div class="legend">${legendHtml()}<span class="drag-hint">バーを左右にドラッグして日程移動・ダブルクリックで編集</span></div></main>${modalHtml()}</div>`;
    requestAnimationFrame(bindGanttDrag);
  }
  function zoomButtons() { return [['day', '日'], ['week', '週'], ['month', '月'], ['fit', '全体表示']].map(([value, label]) => `<button class="segment ${state.zoom === value ? 'active' : ''}" data-action="zoom" data-value="${value}">${label}</button>`).join(''); }
  function timelineBounds(project) { const starts = project.tasks.map(t => t.startDate).concat(project.startDate).filter(Boolean).sort(); const ends = project.tasks.map(t => t.endDate).concat(project.endDate).filter(Boolean).sort(); const start = addDays(starts[0] || todayISO(), -2); const end = addDays(ends[ends.length - 1] || addDays(start, 30), 3); return { start, end, days: daysBetween(start, end) + 1 }; }
  function zoomDayWidth(zoom, days) { if (zoom === 'day') return 30; if (zoom === 'week') return 14; if (zoom === 'month') return 5; return Math.max(3.2, Math.min(14, (window.innerWidth - 285) / days)); }
  function timelineHeader(bounds, dayWidth) {
    let html = ''; let cursor = bounds.start;
    while (cursor <= bounds.end) { const d = parseDate(cursor); let next; let label; if (state.zoom === 'day') { next = addDays(cursor, 1); label = `${d.getUTCMonth() + 1}/${d.getUTCDate()}`; } else if (state.zoom === 'week') { next = addDays(cursor, 7); label = `${d.getUTCMonth() + 1}/${d.getUTCDate()}週`; } else { next = iso(new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 1))); label = `${d.getUTCFullYear()}年${d.getUTCMonth() + 1}月`; } const cellDays = Math.min(daysBetween(cursor, next), daysBetween(cursor, bounds.end) + 1); html += `<span style="width:${cellDays * dayWidth}px">${label}</span>`; cursor = next; }
    return html;
  }
  function taskLabel(t, index, total) { return `<div class="task-label"><span class="type-dot ${TYPES[t.type].className}"></span><button class="task-name" data-action="edit-task" data-id="${t.id}" title="工程を編集">${escapeHtml(t.name)}</button><div class="row-actions"><button data-action="move-task" data-id="${t.id}" data-dir="-1" ${index === 0 ? 'disabled' : ''} title="上へ移動">↑</button><button data-action="move-task" data-id="${t.id}" data-dir="1" ${index === total - 1 ? 'disabled' : ''} title="下へ移動">↓</button><button data-action="edit-task" data-id="${t.id}" title="編集">•••</button></div></div>`; }
  function taskRow(t, index, bounds, dayWidth) { const left = daysBetween(bounds.start, t.startDate) * dayWidth; const duration = Math.max(1, daysBetween(t.startDate, t.endDate) + 1); const width = Math.max(t.type === 'milestone' ? 16 : 8, duration * dayWidth); const milestone = t.type === 'milestone'; return `<div class="timeline-row"><button class="gantt-bar ${TYPES[t.type].className} ${milestone ? 'milestone' : ''}" style="left:${left}px;width:${width}px" data-task-id="${t.id}" data-index="${index}" aria-label="${escapeHtml(t.name)} ${formatDate(t.startDate)}から${formatDate(t.endDate)}" title="${escapeHtml(t.name)}｜${formatDate(t.startDate, true)}〜${formatDate(t.endDate, true)}"><span>${milestone ? '' : escapeHtml(t.name)}</span></button></div>`; }
  function legendHtml() { return Object.values(TYPES).map(type => `<span><i class="${type.className}"></i>${type.label}</span>`).join(''); }
  function printLegendHtml(project) { const client = /(?:様|御中)$/.test(project.clientName.trim()) ? project.clientName : `${project.clientName} 様`; return `<span><i class="type-internal"></i>天野企画</span><span><i class="type-client"></i>${escapeHtml(client)}</span><span><i class="type-photo"></i>撮影</span><span><i class="type-milestone"></i>マイルストーン</span>`; }

  function renderPreview(id) {
    const project = projectById(id); if (!project) { navigate(''); return; }
    const chunks = []; for (let i = 0; i < project.tasks.length; i += 14) chunks.push(project.tasks.slice(i, i + 14));
    app.innerHTML = `<div class="preview-shell"><div class="preview-toolbar"><button class="btn" data-action="back-editor" data-id="${project.id}">← 編集に戻る</button><div><strong>A4横プレビュー</strong><span>${chunks.length > 1 ? `${chunks.length}ページに分割` : '1ページに収まります'}</span></div><button class="btn btn-primary" data-action="print">印刷</button></div><div class="paper-stage">${chunks.map((tasks, i) => printPage(project, tasks, i + 1, chunks.length)).join('')}</div></div>`;
  }
  function printPage(project, tasks, pageNo, totalPages) { const allBounds = timelineBounds(project); return `<article class="a4-page"><header class="print-head"><div><div class="print-kicker">PRODUCTION SCHEDULE</div><h1>${escapeHtml(project.name)}</h1><p>${escapeHtml(project.clientName)} 御中</p></div><dl><div><dt>作成日</dt><dd>${formatDate(todayISO())}</dd></div><div><dt>公開予定日</dt><dd>${escapeHtml(project.publishLabel || formatDate(project.publishDate))}</dd></div></dl></header><div class="print-gantt"><div class="print-label-head">工程</div><div class="print-months">${printMonths(allBounds)}</div>${tasks.map(t => printTaskRow(t, allBounds)).join('')}</div><footer class="print-foot"><div>${printLegendHtml(project)}</div><p>※日程は進行状況・ご確認状況により調整となる場合があります。</p><span>${totalPages > 1 ? `${pageNo} / ${totalPages}` : ''}</span></footer></article>`; }
  function printMonths(bounds) { let cursor = bounds.start; let html = ''; while (cursor <= bounds.end) { const d = parseDate(cursor); const next = iso(new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 1))); const days = Math.min(daysBetween(cursor, next), daysBetween(cursor, bounds.end) + 1); html += `<span style="flex:${days}">${d.getUTCFullYear()}/${d.getUTCMonth() + 1}</span>`; cursor = next; } return html; }
  function printTaskRow(t, bounds) { const left = daysBetween(bounds.start, t.startDate) / bounds.days * 100; const width = Math.max(.6, (daysBetween(t.startDate, t.endDate) + 1) / bounds.days * 100); return `<div class="print-row"><div class="print-task-name"><i class="${TYPES[t.type].className}"></i>${escapeHtml(t.name)}</div><div class="print-track"><span class="print-bar ${TYPES[t.type].className} ${t.type === 'milestone' ? 'milestone' : ''}" style="left:${left}%;width:${width}%"></span></div></div>`; }

  function modalHtml() { if (!state.modal) return ''; if (state.modal.kind === 'task') return taskModal(state.modal.task); if (state.modal.kind === 'project') return projectModal(state.modal.project, state.modal.isNew); if (state.modal.kind === 'data') return dataModal(); return ''; }
  function taskModal(taskData) { const isNew = !taskData.id; return `<div class="modal-backdrop" data-action="cancel-modal"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal-panel><div class="modal-head"><div><span class="eyebrow">TASK</span><h2 id="modal-title">${isNew ? '工程を追加' : '工程を編集'}</h2></div><button class="icon-btn" data-action="cancel-modal" aria-label="閉じる">×</button></div><form data-form="task"><label>工程名<input name="name" required maxlength="80" value="${escapeHtml(taskData.name || '')}"></label><div class="form-grid"><label>開始日<input type="date" name="startDate" required value="${taskData.startDate || ''}"></label><label>終了日<input type="date" name="endDate" required value="${taskData.endDate || ''}"></label></div><label>区分<select name="type">${Object.entries(TYPES).map(([key, value]) => `<option value="${key}" ${taskData.type === key ? 'selected' : ''}>${value.label}</option>`).join('')}</select></label><p class="form-error" aria-live="polite"></p><div class="modal-actions">${isNew ? '' : '<button type="button" class="btn btn-danger" data-action="delete-task">削除</button>'}<span></span><button type="button" class="btn" data-action="cancel-modal">キャンセル</button><button type="submit" class="btn btn-primary">保存</button></div></form></section></div>`; }
  function projectModal(project, isNew) { return `<div class="modal-backdrop" data-action="cancel-modal"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal-panel><div class="modal-head"><div><span class="eyebrow">PROJECT</span><h2 id="modal-title">${isNew ? '新規案件作成' : '案件情報を編集'}</h2></div><button class="icon-btn" data-action="cancel-modal" aria-label="閉じる">×</button></div><form data-form="project"><label>案件名<input name="name" required maxlength="100" value="${escapeHtml(project.name || '')}"></label><label>クライアント名<input name="clientName" required maxlength="100" value="${escapeHtml(project.clientName || '')}"></label><div class="form-grid"><label>制作開始日<input type="date" name="startDate" required value="${project.startDate || ''}"></label><label>制作終了日<input type="date" name="endDate" required value="${project.endDate || ''}"></label></div><div class="form-grid"><label>公開予定日<input type="date" name="publishDate" required value="${project.publishDate || ''}"></label><label>公開予定の表示<input name="publishLabel" placeholder="例：2027年2月下旬" value="${escapeHtml(project.publishLabel || '')}"></label></div><label>ステータス<select name="status">${['予定', '進行中', '確認中', '完了', '保留'].map(s => `<option ${project.status === s ? 'selected' : ''}>${s}</option>`).join('')}</select></label><p class="form-error" aria-live="polite"></p><div class="modal-actions"><span></span><span></span><button type="button" class="btn" data-action="cancel-modal">キャンセル</button><button type="submit" class="btn btn-primary">保存</button></div></form></section></div>`; }
  function dataModal() { const last = localStorage.getItem(BACKUP_KEY); return `<div class="modal-backdrop" data-action="cancel-modal"><section class="modal modal-small" role="dialog" aria-modal="true" aria-labelledby="modal-title" data-modal-panel><div class="modal-head"><div><span class="eyebrow">DATA</span><h2 id="modal-title">データ管理</h2></div><button class="icon-btn" data-action="cancel-modal" aria-label="閉じる">×</button></div><p class="modal-copy">正式な保存先はFirebaseです。JSONは全案件の手動バックアップや移行に利用できます。</p><p class="backup-status">最終バックアップ：${last ? escapeHtml(new Date(last).toLocaleString('ja-JP')) : 'バックアップ未作成'}</p><div class="data-actions"><button class="btn btn-primary" data-action="export-json">JSONをエクスポート</button><label class="btn file-btn">JSONをインポート<input type="file" accept="application/json,.json" data-action="import-json"></label></div><p class="form-error" aria-live="polite"></p><div class="modal-actions"><span></span><span></span><span></span><button class="btn" data-action="cancel-modal">閉じる</button></div></section></div>`; }

  function bindGlobalActions() {
    app.onclick = event => {
      const actionEl = event.target.closest('[data-action]'); if (!actionEl) return; if (actionEl.matches('.modal-backdrop') && event.target.closest('[data-modal-panel]')) return;
      const action = actionEl.dataset.action; const route = currentRoute(); const project = route.id ? projectById(route.id) : null;
      if (action === 'home') navigate(''); else if (action === 'logout') authService.signOut(); else if (action === 'open-project') navigate(`project/${actionEl.dataset.id}`); else if (action === 'preview') navigate(`preview/${actionEl.dataset.id}`); else if (action === 'back-editor') navigate(`project/${actionEl.dataset.id}`); else if (action === 'print') window.print(); else if (action === 'new-project') openProjectModal({}, true); else if (action === 'edit-project') openProjectModal(project, false); else if (action === 'new-task') openTaskModal({ startDate: project.startDate, endDate: project.startDate, type: 'internal' }); else if (action === 'edit-task') openTaskModal(project.tasks.find(t => t.id === actionEl.dataset.id)); else if (action === 'cancel-modal') closeModal(); else if (action === 'delete-task') deleteCurrentTask(); else if (action === 'move-task') moveTask(project, actionEl.dataset.id, Number(actionEl.dataset.dir)); else if (action === 'zoom') { state.zoom = actionEl.dataset.value; render(); } else if (action === 'data') { state.modal = { kind: 'data' }; render(); } else if (action === 'export-json') exportJSON();
    };
    app.onchange = event => { if (event.target.dataset.action === 'cascade') state.cascade = event.target.checked; if (event.target.dataset.action === 'import-json') importJSON(event.target.files[0]); };
    app.onsubmit = event => { event.preventDefault(); if (event.target.dataset.form === 'task') saveTaskForm(event.target); if (event.target.dataset.form === 'project') saveProjectForm(event.target); };
    const firstInput = app.querySelector('.modal input'); if (firstInput) requestAnimationFrame(() => firstInput.focus());
    document.onkeydown = event => { if (event.key === 'Escape' && state.modal) closeModal(); };
  }
  function openTaskModal(taskData) { state.modal = { kind: 'task', task: clone(taskData) }; render(); }
  function openProjectModal(project, isNew) { state.modal = { kind: 'project', project: clone(project), isNew }; render(); }
  function closeModal() { state.modal = null; render(); }
  function showFormError(message) { const el = app.querySelector('.form-error'); if (el) el.textContent = message; }
  function saveTaskForm(form) { const route = currentRoute(); const project = projectById(route.id); if (!project) return; const data = Object.fromEntries(new FormData(form)); if (data.endDate < data.startDate) { showFormError('終了日は開始日以降にしてください。'); return; } const existing = state.modal.task.id && project.tasks.find(t => t.id === state.modal.task.id); if (existing) Object.assign(existing, data); else project.tasks.push({ id: uid('task'), ...data }); touch(project); state.modal = null; render(); }
  function saveProjectForm(form) { const data = Object.fromEntries(new FormData(form)); if (data.endDate < data.startDate) { showFormError('制作終了日は開始日以降にしてください。'); return; } if (state.modal.isNew) { const now = new Date().toISOString(); const project = { id: uid('project'), ...data, createdAt: now, updatedAt: now, tasks: [] }; state.projects.push(project); saveProject(project); state.modal = null; navigate(`project/${project.id}`); } else { const route = currentRoute(); const project = projectById(route.id); Object.assign(project, data); touch(project); state.modal = null; render(); } }
  async function deleteCurrentTask() { const route = currentRoute(); const project = projectById(route.id); const current = state.modal.task; if (!confirm(`「${current.name}」を削除しますか？`)) return; project.tasks = project.tasks.filter(t => t.id !== current.id); state.modal = null; render(); try { await projectRepository.deleteTask(project.id, current.id); await saveProject(project); } catch (error) { state.error = '工程を削除できませんでした。'; console.error(error); render(); } }
  function moveTask(project, taskId, direction) { const index = project.tasks.findIndex(t => t.id === taskId); const target = index + direction; if (index < 0 || target < 0 || target >= project.tasks.length) return; [project.tasks[index], project.tasks[target]] = [project.tasks[target], project.tasks[index]]; touch(project); render(); }
  function touch(project) { project.updatedAt = new Date().toISOString(); saveProject(project); }
  function validateBackup(payload) { if (!payload || payload.version !== 1 || !Array.isArray(payload.projects)) throw new Error('対応していないJSON形式です。'); payload.projects.forEach(project => { if (!project.id || !project.name || !Array.isArray(project.tasks)) throw new Error('案件データに不足があります。'); }); return payload.projects; }
  function exportJSON() { const exportedAt = new Date().toISOString(); const blob = new Blob([JSON.stringify({ version: 1, exportedAt, projects: state.projects }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `web-schedule-${todayISO()}.json`; link.click(); URL.revokeObjectURL(url); localStorage.setItem(BACKUP_KEY, exportedAt); state.modal = null; render(); }
  function importJSON(file) { if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const projects = validateBackup(JSON.parse(reader.result)); if (!confirm(`現在の全案件を、選択したJSONの${projects.length}件で置き換えますか？`)) return; state.saving = true; await projectRepository.replaceAll(projects); state.projects = await projectRepository.loadProjects(); state.saving = false; state.modal = null; navigate(''); render(); } catch (error) { state.saving = false; showFormError(error.message); } }; reader.readAsText(file); }

  function bindGanttDrag() {
    const timeline = app.querySelector('.timeline-scroll');
    const header = app.querySelector('.timeline-head-wrap');
    if (timeline && header) timeline.onscroll = () => { header.scrollLeft = timeline.scrollLeft; };
    app.querySelectorAll('.gantt-bar').forEach(bar => {
      bar.ondblclick = event => { event.preventDefault(); const project = projectById(currentRoute().id); openTaskModal(project.tasks.find(t => t.id === bar.dataset.taskId)); };
      bar.onpointerdown = event => { if (event.button !== 0) return; event.preventDefault(); const timeline = app.querySelector('.timeline-scroll'); const dayWidth = Number(timeline.dataset.dayWidth); const startX = event.clientX; let delta = 0; let moved = false; bar.setPointerCapture(event.pointerId); bar.classList.add('dragging'); bar.onpointermove = moveEvent => { delta = Math.round((moveEvent.clientX - startX) / dayWidth); moved = moved || Math.abs(moveEvent.clientX - startX) > 3; bar.style.transform = `translateX(${delta * dayWidth}px)`; }; bar.onpointerup = () => { bar.classList.remove('dragging'); bar.style.transform = ''; bar.onpointermove = null; bar.onpointerup = null; if (moved && delta !== 0) shiftTasks(Number(bar.dataset.index), delta); }; };
    });
  }
  function shiftTasks(index, delta) { const project = projectById(currentRoute().id); const targets = state.cascade ? project.tasks.slice(index) : [project.tasks[index]]; targets.forEach(t => { t.startDate = addDays(t.startDate, delta); t.endDate = addDays(t.endDate, delta); }); touch(project); render(); }
  window.addEventListener('hashchange', () => { if (state.user) render(); });
  window.addEventListener('resize', () => { if (currentRoute().page === 'editor' && state.zoom === 'fit') render(); });
  function renderLogin(message = '') { document.body.classList.remove('preview-mode'); app.innerHTML = `<main class="auth-shell"><section class="login-card"><p class="login-kicker">社内ツール</p><h1>制作スケジュール管理</h1><p class="login-lead">許可された社内スタッフのみ利用できます。</p><form id="login-form" class="login-form"><label>メールアドレス<input name="email" type="email" autocomplete="username" required></label><label>パスワード<input name="password" type="password" autocomplete="current-password" required></label><p class="auth-error" role="alert">${escapeHtml(message)}</p><button class="btn btn-primary" type="submit">ログイン</button></form></section></main>`; document.querySelector('#login-form').onsubmit = async event => { event.preventDefault(); const button = event.target.querySelector('button'); const data = new FormData(event.target); button.disabled = true; button.textContent = 'ログイン中…'; try { await authService.signIn(String(data.get('email')).trim(), String(data.get('password'))); } catch { renderLogin('メールアドレスまたはパスワードを確認してください。'); } }; }
  function renderLoading(message = 'ログイン状態を確認しています…') { app.innerHTML = `<main class="auth-shell"><section class="login-card" aria-live="polite"><p class="login-kicker">社内ツール</p><h1>制作スケジュール管理</h1><p class="muted">${escapeHtml(message)}</p></section></main>`; }
  renderLoading();
  authService.observe(async user => {
    state.user = null; state.projects = [];
    if (!user) { renderLogin(); return; }
    renderLoading('スタッフ権限と共有データを確認しています…');
    try {
      if (!await projectRepository.isStaff(user.uid)) { await authService.signOut(); renderLogin('このアカウントは利用を許可されていません。'); return; }
      state.user = user;
      state.projects = await projectRepository.loadProjects();
      render();
    } catch (error) {
      console.error(error);
      await authService.signOut();
      renderLogin('共有データへ接続できません。Firestoreの設定を確認してください。');
    }
  });
